### ISSUE TITLE
local_settings.py secret key instruction broken in Python3

### ISSUE THREAD

**Issue by rob-hills** [twintechlabs/flaskdash#4]
In the local_settings.py, there is the recommendation to run:
`python -c "import os; print str(os.urandom(24));"`
to generate a secret key.

On my system (Ubuntu 18.04), this command throws an error in Python 3:
```
python3 -c "import os; print repr(os.urandom(24));"
  File "<string>", line 1
    import os; print repr(os.urandom(24));
                        ^
```
Googling throws up various working alternatives.  The one suggested in https://github.com/diamond-org/flask-diamond/issues/24 looks pretty neat to me and works in both Python 2.7.15 and 3.6.7 on my system.

Based on the link above, the following line is much longer than the current suggestion in local_settings.py, but it works in Python 2 and 3:

`python -c "from __future__ import print_function; import string; import random; print(''.join([random.choice(string.ascii_letters + string.digits + string.punctuation) for x in range(24)]));"`

**Comment by twintechlabs** [comment]
Thank you for the feedback.  Should be fixed now.
