### ISSUE TITLE
Form "Reset" button doesn't work as expected

### ISSUE THREAD

**Issue by rob-hills** [twintechlabs/flaskdash#5]
The "Edit" forms in this project (eg the User Profile form) have at the bottom two buttons, one labelled "submit" and the other "reset".

I expected the "reset" buttons to discard any edits and either refresh the "Edit" form with the original data, or return to the previous screen.  Instead it seems to function exactly the same way as the "submit" button, ie it saves all edits.

**Comment by twintechlabs** [comment]
Fixed in most recent build.
